### ISSUE TITLE
Required: GitHub repo name/title change

### ISSUE THREAD

**Issue by serbinsh** [TESTgroup-BNL/PLSR_for_plant_trait_prediction#14]
I called this "How_to_PLSR" as a placeholder.  We should probably change this at some point so its a bit more descriptive and matches the paper

**Comment by serbinsh** [comment]
Folks, what do we think about the repo name?  I think we should change it but to what?  @TESTgroup-BNL/testgroup_members

**Comment by regnans** [comment]
How about: "PLSR_for_plant_trait_prediction"

**Comment by serbinsh** [comment]
Accepted.  Renamed.
