### ISSUE TITLE
Using the Jacnife method to determine NoC

### ISSUE THREAD

**Issue by JulienLamour** [TESTgroup-BNL/PLSR_for_plant_trait_prediction#16]
Why not using the default method from the pls package to determine the number of components, ie the function selectNcomp? I think it would simplify the code and the manuscript. See for example p13 of the pls manual. https://cran.r-project.org/web/packages/pls/vignettes/pls-manual.pdf . But maybe you didnt like that?

**Comment by serbinsh** [comment]
@JulienLamour does it work pretty well now?  In the past it didnt work well.  Also the example in the script is explicit and thus not really dependent on the package itself.  I wonder if thats what we want?  That is to show how its done instead of using the built in version?  Open to ideas on this

**Comment by neo0351** [comment]
@serbinsh I agree with being as explicit as possible for this.  It's a teaching tool, so sometimes showing what is going on is important, even if the code isn't as pretty or as efficient as it could be.

**Comment by JulienLamour** [comment]
I tried their function and it seems to work. I understand your idea about being as explicit as possible, but in that case we will have to modify the code to make it a real jacknife or to change the name of the method. Indeed, since there is replacement and since the total of the sub samples is not equal to the total number of observations, I dont think we can call the method jacknife.

**Comment by neo0351** [comment]
@JulienLamour Do you think we should use their function, or do you think there's value to just renaming our code to something like "resample" be being more explicit?  My vote still goes to our code (change the name if needed) for the reasons @serbinsh stated.

**Comment by serbinsh** [comment]
All good points.  Julien I’ll take a look tomorrow do you have an example where you use the old version?  I can look but maybe warming to your idea to leverage that but also explain what we are doing and why in more detail .

[iphone]

On Aug 26, 2020, at 17:56, Jeremiah <notifications@github.com> wrote:

﻿

@JulienLamour<https://github.com/JulienLamour> Do you think we should use their function, or do you think there's value to just renaming our code to something like "resample" be being more explicit? My vote still goes to our code (change the name if needed) for the reasons @serbinsh<https://github.com/serbinsh> stated.
