### ISSUE TITLE
Create a new "plsr_companion" R package to contain custom TEST group functions/approaches?

### ISSUE THREAD

**Issue by serbinsh** [TESTgroup-BNL/PLSR_for_plant_trait_prediction#29]
Given the increased complexity and interest in using the example PLSR R script, the question now is whether we should create a small R package containing the functions developed for the scripts in order to make it easier to find and use these functions in custom fitting scripts?  The idea would be this package would be a companion to the standard PLS package containing custom functions to make the approach easier.  It could also contain 1 or 2 example datasets.

**Comment by neo0351** [comment]
I vote yes.  A pain now, but I think in the long run it will be easier.
