### ISSUE TITLE
Check package versions

### ISSUE THREAD

**Issue by neo0351** [TESTgroup-BNL/PLSR_for_plant_trait_prediction#35]
Check we use all loaded packages and all package versions are somewhere.

**Comment by serbinsh** [comment]
Also see PR #34 which is related (sort of)

**Comment by serbinsh** [comment]
At least two reqiurements are

remotes >= 2.2.0
ggplot2 >=3.3.2

**Comment by neo0351** [comment]
Sounds like now would be a good time to check to see if we are using all the packages we load?

**Comment by serbinsh** [comment]
Correct

**Comment by neo0351** [comment]
dependancies added to readme
