### ISSUE TITLE
Edits suggested by Angie 9/23

### ISSUE THREAD

**Issue by angieburnett** [TESTgroup-BNL/PLSR_for_plant_trait_prediction#42]
Change LMA to SLA in filename etc for expanded_spectra-trait_kit_lma_plsr_example.R
Rename files without 'expanded' and delete simple file.

**Comment by serbinsh** [comment]
Will do all except I am updating the "simple" example and will keep it as an example of a very basic fit

**Comment by serbinsh** [comment]
Included in PR #44
