### ISSUE TITLE
Correct the x axis of some plots

### ISSUE THREAD

**Issue by JulienLamour** [TESTgroup-BNL/PLSR_for_plant_trait_prediction#46]
There are some wrong xlab in the coefs plots. they go from 0 to 1500 instead of 500 to 2500

**Comment by serbinsh** [comment]
yeah ugh I noticed that!  :(

**Comment by serbinsh** [comment]
@JulienLamour did you want to make the fix or me? I think we just need to correct the x axis in the figure function

**Comment by neo0351** [comment]
@JulienLamour looks like you completed this one?

**Comment by JulienLamour** [comment]
Yes sorry for not closing it
