### ISSUE TITLE
Scales package - do we use it?

### ISSUE THREAD

**Issue by serbinsh** [TESTgroup-BNL/PLSR_for_plant_trait_prediction#60]
@neo0351 we have scales listed as a depends. not sure I know where we use it?

**Comment by neo0351** [comment]
I couldn't find where we use it.  It appears to be loaded twice, in apply_sserbin and the simple example, but I don't see it being used.  At least according to the package NCmisc

**Comment by neo0351** [comment]
Maybe I should look at all the packages we use and see if there is any others we call for but don't use?

**Comment by serbinsh** [comment]
Thanks!  @neo0351 lets wait for a full house cleaning until I have the base package version PR done

**Comment by serbinsh** [comment]
@neo0351 OK so I know where we use "scales"

We use it to generate the "alpha" transparency in some of the plotting, like in the plotrix::plotCI

```
alpha(colour, alpha = NA)
```

**Comment by neo0351** [comment]
Ok, I see how I missed it.  "alpha" is also part of ggplot2.  I was looking in the wrong part of the output.

**Comment by neo0351** [comment]
We should check our code for issues like this and make sure we are using `package::function` where there are conflicts like this alpha thing.

**Comment by serbinsh** [comment]
Agreed, the fix for this is to make sure the examples have scales::alpha()
