### ISSUE TITLE
Update README to help new R users install and run package

### ISSUE THREAD

**Issue by serbinsh** [TESTgroup-BNL/PLSR_for_plant_trait_prediction#70]
@regnans 
https://github.com/TESTgroup-BNL/PLSR_for_plant_trait_prediction/issues/69#issuecomment-778879497

Assigning updating the README to you so you can add the suggested changes you were thinking about. Feel free to make the edits right in GH.

**Comment by regnans** [comment]
I've added a Getting Started section to help smooth the way for beginners. As I am a beginner, I didn't know all of the answers - need to add detail on the best way to get the code from GitHub to RStudio (or whatever is being used). Will also need a language check on this section to make sure I've used correct terminology.

**Comment by serbinsh** [comment]
Done
